[project]
name = "manim-animation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kokoro-onnx>=0.4.8",
    "manim>=0.19.0",
    "misaki[en]>=0.9.4",
    "soundfile>=0.13.1",
]
